//SCOMPOSIZIONE DEL PROBLEMA//

//INSERISCI I KM//
//INSERISCI L'ETA'//
//LA TARIFFA AL KM SARA' DI 0,21//
//I MINORENNI AVRANNO UNO SCONTO PARI AL 20% (<18)//
//GLI OVER 65 AVRANNO UNO SCONTO PARI AL 40% (>65)//
//ALTRIMENTI NON CI SARA' NESSUNO SCONTO//

//PASSAGGI DA ESEGUIRE//

//REALIZZARE CAMPO INPUT PER I KM//
//REALIZZARE CAMPO INPUT PER L'ETA'//
//CALCOLO DEL PREZZO TOTALE TRAMITE PRESSIONE DI UN PULSANTE//
//STAMPARE A VIDEO I RISULTATI//

